(()=>{
const els=[...document.querySelectorAll('.reveal')];if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.15});els.forEach(e=>io.observe(e))}else els.forEach(e=>e.classList.add('in'));
const dialog=document.querySelector('#menuDialog'),img=document.querySelector('#menuImage'),label=document.querySelector('#menuLabel');document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>{img.src=b.dataset.menu;img.alt=b.dataset.label;label.textContent=b.dataset.label;dialog.showModal()}));dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
const canvas=document.querySelector('#ink'),gl=canvas.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:false});if(!gl){canvas.style.display='none';return}
const V=`#version 300 es\nprecision highp float;in vec2 p;out vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
const adv=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D vel,dye;uniform vec2 px;uniform float dt;void main(){vec2 v=texture(vel,uv).xy;o=texture(dye,uv-dt*v*px)*.995;}`;
const advv=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D vel;uniform vec2 px;uniform float dt;void main(){vec2 v=texture(vel,uv).xy;o=vec4(texture(vel,uv-dt*v*px).xy*.992,0,1);}`;
const divs=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D vel;uniform vec2 px;void main(){float l=texture(vel,uv-vec2(px.x,0)).x,r=texture(vel,uv+vec2(px.x,0)).x,b=texture(vel,uv-vec2(0,px.y)).y,t=texture(vel,uv+vec2(0,px.y)).y;o=vec4(.5*(r-l+t-b),0,0,1);}`;
const press=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D pressure,div;uniform vec2 px;void main(){float l=texture(pressure,uv-vec2(px.x,0)).x,r=texture(pressure,uv+vec2(px.x,0)).x,b=texture(pressure,uv-vec2(0,px.y)).x,t=texture(pressure,uv+vec2(0,px.y)).x,d=texture(div,uv).x;o=vec4((l+r+b+t-d)*.25,0,0,1);}`;
const grad=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D pressure,vel;uniform vec2 px;void main(){float l=texture(pressure,uv-vec2(px.x,0)).x,r=texture(pressure,uv+vec2(px.x,0)).x,b=texture(pressure,uv-vec2(0,px.y)).x,t=texture(pressure,uv+vec2(0,px.y)).x;o=vec4(texture(vel,uv).xy-.5*vec2(r-l,t-b),0,1);}`;
const splat=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D base;uniform vec2 point;uniform vec3 value;uniform float radius,aspect;void main(){vec2 d=uv-point;d.x*=aspect;float a=exp(-dot(d,d)/radius);o=texture(base,uv)+vec4(value*a,0);}`;
const display=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D dye;uniform float mode;void main(){vec3 c=texture(dye,uv).rgb;float n=sin((uv.x+uv.y)*34.+c.r*8.)*.06;if(mode>1.5)c=mix(c,vec3(c.b*.55,c.r*.15,c.r*.7),.45);else if(mode>.5)c=mix(c,vec3(1.,.46,.12),.24);else c+=vec3(.28,.01,.08)*n;c=1.-exp(-c*1.7);float a=clamp(max(c.r,max(c.g,c.b))*1.65,0.,.82);o=vec4(c,a);}`;
function sh(t,s){const q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}function pg(f){const q=gl.createProgram();gl.attachShader(q,sh(gl.VERTEX_SHADER,V));gl.attachShader(q,sh(gl.FRAGMENT_SHADER,f));gl.linkProgram(q);return q}const P={adv:pg(adv),advv:pg(advv),div:pg(divs),press:pg(press),grad:pg(grad),splat:pg(splat),display:pg(display)};
const vao=gl.createVertexArray();gl.bindVertexArray(vao);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);for(const p of Object.values(P)){const a=gl.getAttribLocation(p,'p');gl.useProgram(p);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0)}
let W,H;function target(){const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA16F,W,H,0,gl.RGBA,gl.HALF_FLOAT,null);const fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);return{tex,fb}}function pair(){return{a:target(),b:target(),swap(){[this.a,this.b]=[this.b,this.a]}}}let vel,dye,pressure,div;function init(){W=Math.max(180,Math.min(560,Math.round(innerWidth*(innerWidth<700?.38:.34))));H=Math.max(180,Math.min(560,Math.round(innerHeight*(innerWidth<700?.38:.34))));canvas.width=innerWidth;canvas.height=innerHeight;vel=pair();dye=pair();pressure=pair();div=target()}init();
function draw(p,out,bindings,extra={}){gl.useProgram(p);gl.bindFramebuffer(gl.FRAMEBUFFER,out?out.fb:null);gl.viewport(0,0,out?W:canvas.width,out?H:canvas.height);let u=0;for(const[k,v]of Object.entries(bindings)){const l=gl.getUniformLocation(p,k);gl.activeTexture(gl.TEXTURE0+u);gl.bindTexture(gl.TEXTURE_2D,v.tex);gl.uniform1i(l,u++)}for(const[k,v]of Object.entries(extra)){const l=gl.getUniformLocation(p,k);if(l===null)continue;Array.isArray(v)?(v.length===2?gl.uniform2fv(l,v):gl.uniform3fv(l,v)):gl.uniform1f(l,v)}gl.drawArrays(gl.TRIANGLES,0,6)}
let lastX=.5,lastY=.5,mode=0;function sectionMode(){const y=scrollY+innerHeight*.5,m=document.querySelector('.signature-miso'),t=document.querySelector('.signature-tsubasa');mode=t&&y>=t.offsetTop?2:m&&y>=m.offsetTop?1:0}addEventListener('scroll',sectionMode,{passive:true});sectionMode();
function inject(x,y,dx,dy,burst=1){const aspect=innerWidth/innerHeight;draw(P.splat,vel.b,{base:vel.a},{point:[x,y],value:[dx*1450*burst,dy*1450*burst,0],radius:mode===2?.0028:.0022,aspect});vel.swap();let col=mode===1?[1.7,.38,.05]:mode===2?[.42,.05,1.65]:[1.55,.02,.3];draw(P.splat,dye.b,{base:dye.a},{point:[x,y],value:col.map(v=>v*burst),radius:mode===1?.008:.006,aspect});dye.swap()}
addEventListener('pointermove',e=>{const x=e.clientX/innerWidth,y=1-e.clientY/innerHeight;inject(x,y,x-lastX,y-lastY,1.35);lastX=x;lastY=y},{passive:true});addEventListener('pointerdown',e=>inject(e.clientX/innerWidth,1-e.clientY/innerHeight,.035,.025,3.2),{passive:true});addEventListener('touchmove',e=>{const p=e.touches[0];if(p){const x=p.clientX/innerWidth,y=1-p.clientY/innerHeight;inject(x,y,x-lastX,y-lastY,1.7);lastX=x;lastY=y}},{passive:true});
let last=performance.now(),seed=0;function loop(now){const dt=Math.min(.023,(now-last)/1000);last=now;const px=[1/W,1/H];draw(P.advv,vel.b,{vel:vel.a},{px,dt:dt*32});vel.swap();draw(P.div,div,{vel:vel.a},{px});for(let i=0;i<18;i++){draw(P.press,pressure.b,{pressure:pressure.a,div},{px});pressure.swap()}draw(P.grad,vel.b,{pressure:pressure.a,vel:vel.a},{px});vel.swap();draw(P.adv,dye.b,{vel:vel.a,dye:dye.a},{px,dt:dt*28});dye.swap();if(seed++%34===0){if(mode===1)inject(.25+Math.random()*.5,.2+Math.random()*.16,(Math.random()-.5)*.008,.018,1.35);else if(mode===2)inject(.25+Math.random()*.5,.35+Math.random()*.3,(Math.random()-.5)*.014,.006,1.15);else inject(.18+Math.random()*.64,.2+Math.random()*.55,(Math.random()-.5)*.01,.01,1.2)}gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);draw(P.display,null,{dye:dye.a},{mode});gl.disable(gl.BLEND);requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();