(()=>{
const els=[...document.querySelectorAll('.reveal')];if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.15});els.forEach(e=>io.observe(e))}else els.forEach(e=>e.classList.add('in'));
const dialog=document.querySelector('#menuDialog'),img=document.querySelector('#menuImage'),label=document.querySelector('#menuLabel');document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>{img.src=b.dataset.menu;img.alt=b.dataset.label;label.textContent=b.dataset.label;dialog.showModal()}));dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
const canvas=document.querySelector('#ink');const gl=canvas.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:false});if(!gl){canvas.style.display='none';return}
const V=`#version 300 es\nprecision highp float;in vec2 p;out vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
const adv=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D vel;uniform sampler2D dye;uniform vec2 px;uniform float dt;void main(){vec2 v=texture(vel,uv).xy;o=texture(dye,uv-dt*v*px);o*=.996;}`;
const advv=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D vel;uniform vec2 px;uniform float dt;void main(){vec2 v=texture(vel,uv).xy;vec2 q=texture(vel,uv-dt*v*px).xy;o=vec4(q*.994,0.,1.);}`;
const divs=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D vel;uniform vec2 px;void main(){float l=texture(vel,uv-vec2(px.x,0)).x,r=texture(vel,uv+vec2(px.x,0)).x,b=texture(vel,uv-vec2(0,px.y)).y,t=texture(vel,uv+vec2(0,px.y)).y;o=vec4(.5*(r-l+t-b),0,0,1);}`;
const press=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D pressure;uniform sampler2D div;uniform vec2 px;void main(){float l=texture(pressure,uv-vec2(px.x,0)).x,r=texture(pressure,uv+vec2(px.x,0)).x,b=texture(pressure,uv-vec2(0,px.y)).x,t=texture(pressure,uv+vec2(0,px.y)).x,d=texture(div,uv).x;o=vec4((l+r+b+t-d)*.25,0,0,1);}`;
const grad=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D pressure;uniform sampler2D vel;uniform vec2 px;void main(){float l=texture(pressure,uv-vec2(px.x,0)).x,r=texture(pressure,uv+vec2(px.x,0)).x,b=texture(pressure,uv-vec2(0,px.y)).x,t=texture(pressure,uv+vec2(0,px.y)).x;vec2 v=texture(vel,uv).xy-.5*vec2(r-l,t-b);o=vec4(v,0,1);}`;
const splat=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D base;uniform vec2 point;uniform vec3 value;uniform float radius;uniform float aspect;void main(){vec2 d=uv-point;d.x*=aspect;float a=exp(-dot(d,d)/radius);o=texture(base,uv)+vec4(value*a,0);}`;
const display=`#version 300 es\nprecision highp float;in vec2 uv;out vec4 o;uniform sampler2D dye;void main(){vec3 c=texture(dye,uv).rgb;c=1.-exp(-c*1.35);float a=clamp(max(c.r,max(c.g,c.b))*1.35,0.,.72);o=vec4(c,a);}`;
function shader(type,s){const q=gl.createShader(type);gl.shaderSource(q,s);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}function prog(f){const q=gl.createProgram();gl.attachShader(q,shader(gl.VERTEX_SHADER,V));gl.attachShader(q,shader(gl.FRAGMENT_SHADER,f));gl.linkProgram(q);return q}const P={adv:prog(adv),advv:prog(advv),div:prog(divs),press:prog(press),grad:prog(grad),splat:prog(splat),display:prog(display)};
const vao=gl.createVertexArray();gl.bindVertexArray(vao);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);for(const p of Object.values(P)){const a=gl.getAttribLocation(p,'p');gl.useProgram(p);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0)}
let W=256,H=256;function target(){const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA16F,W,H,0,gl.RGBA,gl.HALF_FLOAT,null);const fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);return{tex,fb}}function pair(){return{a:target(),b:target(),swap(){[this.a,this.b]=[this.b,this.a]}}}let vel,dye,pressure,div;function init(){W=Math.max(128,Math.min(420,Math.round(innerWidth*.28)));H=Math.max(128,Math.min(420,Math.round(innerHeight*.28)));canvas.width=innerWidth;canvas.height=innerHeight;vel=pair();dye=pair();pressure=pair();div=target()}init();addEventListener('resize',()=>{canvas.width=innerWidth;canvas.height=innerHeight},{passive:true});
function tex(p,n,t){const l=gl.getUniformLocation(p,n);if(l!==null){gl.activeTexture(gl.TEXTURE0+t);gl.bindTexture(gl.TEXTURE_2D,t);gl.uniform1i(l,t)}}function draw(p,out,bindings,extra={}){gl.useProgram(p);gl.bindFramebuffer(gl.FRAMEBUFFER,out?out.fb:null);gl.viewport(0,0,out?W:canvas.width,out?H:canvas.height);let u=0;for(const[k,v]of Object.entries(bindings)){const l=gl.getUniformLocation(p,k);gl.activeTexture(gl.TEXTURE0+u);gl.bindTexture(gl.TEXTURE_2D,v.tex);gl.uniform1i(l,u++)}for(const[k,v]of Object.entries(extra)){const l=gl.getUniformLocation(p,k);if(!l)continue;if(Array.isArray(v)){if(v.length===2)gl.uniform2fv(l,v);else gl.uniform3fv(l,v)}else gl.uniform1f(l,v)}gl.drawArrays(gl.TRIANGLES,0,6)}
let pointer={x:.5,y:.5,px:.5,py:.5,down:false};function inject(x,y,dx,dy,burst=1){const aspect=innerWidth/innerHeight;draw(P.splat,vel.b,{base:vel.a},{point:[x,y],value:[dx*950*burst,dy*950*burst,0],radius:.0018,aspect});vel.swap();const hue=(performance.now()*.00004+x*.2)%1;const col=hue<.5?[1.5,.05,.18]:[.55,.04,1.15];draw(P.splat,dye.b,{base:dye.a},{point:[x,y],value:col.map(v=>v*burst),radius:.0045,aspect});dye.swap()}
addEventListener('pointermove',e=>{const x=e.clientX/innerWidth,y=1-e.clientY/innerHeight;inject(x,y,x-pointer.x,y-pointer.y,1);pointer.x=x;pointer.y=y},{passive:true});addEventListener('pointerdown',e=>{inject(e.clientX/innerWidth,1-e.clientY/innerHeight,.03,.02,2.5)},{passive:true});
let last=performance.now(),seed=0;function loop(now){const dt=Math.min(.022,(now-last)/1000);last=now;const px=[1/W,1/H];draw(P.advv,vel.b,{vel:vel.a},{px,dt:dt*28});vel.swap();draw(P.div,div,{vel:vel.a},{px});for(let i=0;i<14;i++){draw(P.press,pressure.b,{pressure:pressure.a,div},{px});pressure.swap()}draw(P.grad,vel.b,{pressure:pressure.a,vel:vel.a},{px});vel.swap();draw(P.adv,dye.b,{vel:vel.a,dye:dye.a},{px,dt:dt*24});dye.swap();if((seed++%90)===0)inject(.2+Math.random()*.6,.2+Math.random()*.55,.006*(Math.random()-.5),.01,1.15);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);draw(P.display,null,{dye:dye.a});gl.disable(gl.BLEND);requestAnimationFrame(loop)}requestAnimationFrame(loop)
})();