(()=>{
const canvases=[...document.querySelectorAll('.fx-canvas[data-effect="steam"]')];if(!canvases.length)return;
const fine=matchMedia('(hover:hover) and (pointer:fine)').matches;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const V=`#version 300 es
in vec2 a;out vec2 uv;void main(){uv=a*.5+.5;gl_Position=vec4(a,0.,1.);}`;
const F=`#version 300 es
precision highp float;in vec2 uv;out vec4 o;uniform float time;uniform vec2 source;uniform vec2 mouse;uniform vec2 mvel;uniform float hasMouse;
float hash(vec2 p){p=fract(p*vec2(127.1,311.7));p+=dot(p,p+34.17);return fract(p.x*p.y);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}
float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+vec2(9.7,13.1);a*=.5;}return v;}
void main(){vec2 p=vec2(uv.x,1.-uv.y);float rise=source.y-p.y;if(rise<0.||rise>.62){o=vec4(0);return;}float nA=fbm(vec2(p.y*7.-time*.22,p.y*3.+time*.11));float nB=fbm(vec2(p.x*10.+time*.18,p.y*11.-time*.28));float nC=fbm(vec2(p.x*22.-time*.31,p.y*18.+time*.16));float center=source.x+sin(rise*8.+time*.72)*.020+sin(rise*17.-time*.41)*.010+(nA-.5)*.050;float md=distance(p,mouse);float push=hasMouse*exp(-md*md/.022);center+=push*mvel.x*.0055;p.y+=push*mvel.y*.0018;float width=.012+rise*.105;float dx=(p.x-center)/width;float body=exp(-dx*dx*1.55);float tex=.42+.50*nB+.30*nC;float plume=body*tex;float edge=exp(-dx*dx*4.5)*(.25+.55*nA);float fade=smoothstep(0.,.028,rise)*(1.-smoothstep(.40,.62,rise));float breakup=.65+.35*smoothstep(.18,.82,nC+nB*.25);float s=(plume*.82+edge*.30)*fade*breakup;float a=clamp(s*.34,0.,.34);vec3 col=mix(vec3(.78,.83,.87),vec3(1.),smoothstep(.05,.55,s));o=vec4(col,a);}`;
function make(c){const gl=c.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)return null;const sh=(t,s)=>{const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x};const p=gl.createProgram();gl.attachShader(p,sh(gl.VERTEX_SHADER,V));gl.attachShader(p,sh(gl.FRAGMENT_SHADER,F));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));const vao=gl.createVertexArray();gl.bindVertexArray(vao);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(p,'a');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const u={time:gl.getUniformLocation(p,'time'),source:gl.getUniformLocation(p,'source'),mouse:gl.getUniformLocation(p,'mouse'),mvel:gl.getUniformLocation(p,'mvel'),hasMouse:gl.getUniformLocation(p,'hasMouse')};const state={mouse:[.5,.5],mvel:[0,0],hasMouse:0};function resize(){const r=c.getBoundingClientRect();const w=r.width<700?180:256;c.width=w;c.height=Math.max(128,Math.round(w*r.height/r.width));gl.viewport(0,0,c.width,c.height)}resize();return{state,resize,draw(t,profile){gl.useProgram(p);gl.bindVertexArray(vao);gl.viewport(0,0,c.width,c.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);const src=profile==='tsubasa'?[.53,.58]:[.555,.575];gl.uniform1f(u.time,reduced?0:t*.001);gl.uniform2f(u.source,src[0],src[1]);gl.uniform2f(u.mouse,state.mouse[0],state.mouse[1]);gl.uniform2f(u.mvel,state.mvel[0],state.mvel[1]);gl.uniform1f(u.hasMouse,state.hasMouse);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.TRIANGLES,0,3);gl.disable(gl.BLEND);state.mvel[0]*=.82;state.mvel[1]*=.82;}}}
const sims=[];for(const c of canvases){let sim;try{sim=make(c)}catch(e){console.error(e)}if(!sim){c.style.display='none';continue}const s={c,sim,profile:c.dataset.profile,visible:false,lastPointer:null};sims.push(s);new IntersectionObserver(e=>s.visible=e[0].isIntersecting,{rootMargin:'120px'}).observe(c);if(fine){c.parentElement.addEventListener('pointermove',e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(x<0||x>1||y<0||y>1){sim.state.hasMouse=0;s.lastPointer=null;return}sim.state.mouse=[x,y];sim.state.hasMouse=1;if(s.lastPointer)sim.state.mvel=[e.clientX-s.lastPointer.x,e.clientY-s.lastPointer.y];s.lastPointer={x:e.clientX,y:e.clientY}},{passive:true});c.parentElement.addEventListener('pointerleave',()=>{sim.state.hasMouse=0;s.lastPointer=null},{passive:true})}}
addEventListener('resize',()=>sims.forEach(s=>s.sim.resize()),{passive:true});let last=0;function frame(t){if(t-last>33){for(const s of sims)if(s.visible)s.sim.draw(t,s.profile);last=t}if(!reduced)requestAnimationFrame(frame)}if(reduced){for(const s of sims)s.sim.draw(0,s.profile)}else requestAnimationFrame(frame);window.__tsubasaEffects={engine:'webgl2-photographic-plume',effects:['steam','gpu-fbm','turbulent-plume','pointer-flow'],interactive:fine,canvasCount:sims.length,targetFps:30,gpu:true};
})();